# コート1面、プレイヤー7人
sequence1:
  coat1:
    home: [1]
    away: [2]
sequence2:
  coat1:
    home: [3]
    away: [4]
sequence3:
  coat1:
    home: [5]
    away: [6]
sequence4:
  coat1:
    home: [7]
    away: [1]
sequence5:
  coat1:
    home: [2]
    away: [3]
sequence6:
  coat1:
    home: [4]
    away: [5]
sequence7:
  coat1:
    home: [6]
    away: [7]
sequence8:
  coat1:
    home: [1]
    away: [3]
sequence9:
  coat1:
    home: [2]
    away: [4]
sequence10:
  coat1:
    home: [5]
    away: [7]
sequence11:
  coat1:
    home: [6]
    away: [1]
sequence12:
  coat1:
    home: [3]
    away: [5]
sequence13:
  coat1:
    home: [2]
    away: [7]
sequence14:
  coat1:
    home: [4]
    away: [6]
sequence15:
  coat1:
    home: [1]
    away: [5]
sequence16:
  coat1:
    home: [3]
    away: [7]
sequence17:
  coat1:
    home: [2]
    away: [6]
sequence18:
  coat1:
    home: [4]
    away: [1]
sequence19:
  coat1:
    home: [5]
    away: [2]
sequence20:
  coat1:
    home: [3]
    away: [6]
sequence21:
  coat1:
    home: [7]
    away: [4]
