# コート1面、プレイヤー8人
sequence1:
  coat1:
    home: [1]
    away: [2]
sequence2:
  coat1:
    home: [3]
    away: [4]
sequence3:
  coat1:
    home: [5]
    away: [6]
sequence4:
  coat1:
    home: [7]
    away: [8]
sequence5:
  coat1:
    home: [1]
    away: [3]
sequence6:
  coat1:
    home: [2]
    away: [4]
sequence7:
  coat1:
    home: [5]
    away: [7]
sequence8:
  coat1:
    home: [6]
    away: [8]
sequence9:
  coat1:
    home: [1]
    away: [4]
sequence10:
  coat1:
    home: [2]
    away: [3]
sequence11:
  coat1:
    home: [5]
    away: [8]
sequence12:
  coat1:
    home: [6]
    away: [7]
sequence13:
  coat1:
    home: [1]
    away: [5]
sequence14:
  coat1:
    home: [2]
    away: [6]
sequence15:
  coat1:
    home: [3]
    away: [7]
sequence16:
  coat1:
    home: [4]
    away: [8]
sequence17:
  coat1:
    home: [1]
    away: [6]
sequence18:
  coat1:
    home: [2]
    away: [7]
sequence19:
  coat1:
    home: [3]
    away: [8]
sequence20:
  coat1:
    home: [4]
    away: [5]
sequence21:
  coat1:
    home: [1]
    away: [7]
sequence22:
  coat1:
    home: [2]
    away: [8]
sequence23:
  coat1:
    home: [3]
    away: [5]
sequence24:
  coat1:
    home: [4]
    away: [6]
sequence25:
  coat1:
    home: [1]
    away: [8]
sequence26:
  coat1:
    home: [2]
    away: [5]
sequence27:
  coat1:
    home: [3]
    away: [6]
sequence28:
  coat1:
    home: [4]
    away: [7]
