# コート1面、プレイヤー7人
sequence1:
  coat1:
    home: [1, 2]
    away: [3, 4]
sequence2:
  coat1:
    home: [1, 5]
    away: [6, 7]
sequence3:
  coat1:
    home: [2, 3]
    away: [5, 6]
sequence4:
  coat1:
    home: [4, 7]
    away: [2, 5]
sequence5:
  coat1:
    home: [1, 3]
    away: [6, 7]
sequence6:
  coat1:
    home: [2, 4]
    away: [5, 6]
sequence7:
  coat1:
    home: [1, 7]
    away: [3, 5]
sequence8:
  coat1:
    home: [2, 6]
    away: [4, 7]
sequence9:
  coat1:
    home: [1, 5]
    away: [3, 6]
sequence10:
  coat1:
    home: [2, 7]
    away: [4, 5]
sequence11:
  coat1:
    home: [1, 6]
    away: [3, 7]
sequence12:
  coat1:
    home: [2, 5]
    away: [4, 6]
sequence13:
  coat1:
    home: [1, 4]
    away: [3, 5]
sequence14:
  coat1:
    home: [2, 6]
    away: [7, 5]
sequence15:
  coat1:
    home: [1, 3]
    away: [4, 6]
sequence16:
  coat1:
    home: [2, 7]
    away: [5, 6]
sequence17:
  coat1:
    home: [1, 4]
    away: [3, 7]
sequence18:
  coat1:
    home: [2, 5]
    away: [6, 7]
sequence19:
  coat1:
    home: [1, 6]
    away: [3, 4]
sequence20:
  coat1:
    home: [2, 5]
    away: [7, 6]
sequence21:
  coat1:
    home: [1, 7]
    away: [3, 5]
sequence22:
  coat1:
    home: [2, 4]
    away: [6, 7]
sequence23:
  coat1:
    home: [1, 5]
    away: [3, 6]
sequence24:
  coat1:
    home: [2, 7]
    away: [4, 6]
sequence25:
  coat1:
    home: [1, 3]
    away: [5, 7]
sequence26:
  coat1:
    home: [2, 6]
    away: [4, 5]
sequence27:
  coat1:
    home: [1, 4]
    away: [7, 6]
sequence28:
  coat1:
    home: [2, 3]
    away: [5, 7]
sequence29:
  coat1:
    home: [1, 6]
    away: [4, 5]
sequence30:
  coat1:
    home: [2, 7]
    away: [3, 6]
