# コート2面、プレイヤー9人
sequence1:
  coat1:
    home: [1, 2]
    away: [3, 4]
  coat2:
    home: [5, 6]
    away: [7, 8]
sequence2:
  coat1:
    home: [1, 5]
    away: [2, 9]
  coat2:
    home: [3, 7]
    away: [4, 6]
sequence3:
  coat1:
    home: [1, 3]
    away: [5, 9]
  coat2:
    home: [2, 8]
    away: [6, 7]
sequence4:
  coat1:
    home: [1, 7]
    away: [2, 4]
  coat2:
    home: [3, 5]
    away: [8, 9]
sequence5:
  coat1:
    home: [1, 6]
    away: [2, 3]
  coat2:
    home: [4, 9]
    away: [7, 8]
sequence6:
  coat1:
    home: [1, 8]
    away: [2, 5]
  coat2:
    home: [3, 9]
    away: [6, 7]
sequence7:
  coat1:
    home: [1, 4]
    away: [5, 7]
  coat2:
    home: [2, 6]
    away: [8, 9]
sequence8:
  coat1:
    home: [1, 9]
    away: [3, 8]
  coat2:
    home: [4, 5]
    away: [6, 2]
sequence9:
  coat1:
    home: [2, 7]
    away: [3, 6]
  coat2:
    home: [4, 8]
    away: [5, 9]
sequence10:
  coat1:
    home: [1, 2]
    away: [5, 6]
  coat2:
    home: [3, 4]
    away: [7, 9]
sequence11:
  coat1:
    home: [1, 5]
    away: [3, 7]
  coat2:
    home: [2, 9]
    away: [6, 8]
sequence12:
  coat1:
    home: [1, 3]
    away: [2, 8]
  coat2:
    home: [4, 9]
    away: [5, 7]
sequence13:
  coat1:
    home: [1, 7]
    away: [6, 9]
  coat2:
    home: [2, 4]
    away: [3, 5]
sequence14:
  coat1:
    home: [1, 6]
    away: [4, 8]
  coat2:
    home: [2, 3]
    away: [7, 9]
sequence15:
  coat1:
    home: [1, 8]
    away: [3, 9]
  coat2:
    home: [5, 6]
    away: [2, 7]
sequence16:
  coat1:
    home: [1, 4]
    away: [6, 7]
  coat2:
    home: [2, 5]
    away: [8, 9]
sequence17:
  coat1:
    home: [1, 9]
    away: [4, 5]
  coat2:
    home: [3, 8]
    away: [6, 7]
sequence18:
  coat1:
    home: [2, 6]
    away: [3, 9]
  coat2:
    home: [4, 7]
    away: [5, 8]
sequence19:
  coat1:
    home: [1, 2]
    away: [7, 8]
  coat2:
    home: [3, 4]
    away: [5, 6]
sequence20:
  coat1:
    home: [1, 5]
    away: [4, 9]
  coat2:
    home: [2, 3]
    away: [6, 8]
sequence21:
  coat1:
    home: [1, 3]
    away: [6, 9]
  coat2:
    home: [2, 7]
    away: [4, 8]
sequence22:
  coat1:
    home: [1, 7]
    away: [3, 5]
  coat2:
    home: [2, 9]
    away: [6, 8]
sequence23:
  coat1:
    home: [1, 6]
    away: [5, 9]
  coat2:
    home: [3, 7]
    away: [4, 2]
sequence24:
  coat1:
    home: [1, 8]
    away: [4, 6]
  coat2:
    home: [2, 5]
    away: [7, 9]
sequence25:
  coat1:
    home: [1, 4]
    away: [2, 9]
  coat2:
    home: [3, 6]
    away: [5, 8]
sequence26:
  coat1:
    home: [1, 9]
    away: [2, 8]
  coat2:
    home: [4, 5]
    away: [3, 7]
sequence27:
  coat1:
    home: [2, 6]
    away: [4, 9]
  coat2:
    home: [3, 5]
    away: [7, 8]
sequence28:
  coat1:
    home: [1, 2]
    away: [5, 7]
  coat2:
    home: [3, 8]
    away: [4, 6]
sequence29:
  coat1:
    home: [1, 5]
    away: [6, 8]
  coat2:
    home: [2, 3]
    away: [7, 9]
sequence30:
  coat1:
    home: [1, 3]
    away: [4, 7]
  coat2:
    home: [2, 6]
    away: [5, 9]
