# コート2面、プレイヤー16人
sequence1:
  coat1:
    home: [1, 2]
    away: [3, 4]
  coat2:
    home: [5, 6]
    away: [7, 8]
sequence2:
  coat1:
    home: [9, 10]
    away: [11, 12]
  coat2:
    home: [13, 14]
    away: [15, 16]
sequence3:
  coat1:
    home: [1, 5]
    away: [2, 6]
  coat2:
    home: [3, 7]
    away: [4, 8]
sequence4:
  coat1:
    home: [9, 13]
    away: [10, 14]
  coat2:
    home: [11, 15]
    away: [12, 16]
sequence5:
  coat1:
    home: [1, 9]
    away: [2, 10]
  coat2:
    home: [3, 11]
    away: [4, 12]
sequence6:
  coat1:
    home: [5, 13]
    away: [6, 14]
  coat2:
    home: [7, 15]
    away: [8, 16]
sequence7:
  coat1:
    home: [1, 3]
    away: [2, 4]
  coat2:
    home: [5, 7]
    away: [6, 8]
sequence8:
  coat1:
    home: [9, 11]
    away: [10, 12]
  coat2:
    home: [13, 15]
    away: [14, 16]
sequence9:
  coat1:
    home: [1, 13]
    away: [2, 14]
  coat2:
    home: [3, 15]
    away: [4, 16]
sequence10:
  coat1:
    home: [5, 9]
    away: [6, 10]
  coat2:
    home: [7, 11]
    away: [8, 12]
sequence11:
  coat1:
    home: [1, 7]
    away: [2, 8]
  coat2:
    home: [3, 5]
    away: [4, 6]
sequence12:
  coat1:
    home: [9, 15]
    away: [10, 16]
  coat2:
    home: [11, 13]
    away: [12, 14]
sequence13:
  coat1:
    home: [1, 11]
    away: [2, 12]
  coat2:
    home: [3, 9]
    away: [4, 10]
sequence14:
  coat1:
    home: [5, 15]
    away: [6, 16]
  coat2:
    home: [7, 13]
    away: [8, 14]
sequence15:
  coat1:
    home: [1, 15]
    away: [2, 16]
  coat2:
    home: [3, 13]
    away: [4, 14]
sequence16:
  coat1:
    home: [5, 11]
    away: [6, 12]
  coat2:
    home: [7, 9]
    away: [8, 10]
sequence17:
  coat1:
    home: [1, 6]
    away: [2, 5]
  coat2:
    home: [3, 8]
    away: [4, 7]
sequence18:
  coat1:
    home: [9, 14]
    away: [10, 13]
  coat2:
    home: [11, 16]
    away: [12, 15]
sequence19:
  coat1:
    home: [1, 10]
    away: [2, 9]
  coat2:
    home: [3, 12]
    away: [4, 11]
sequence20:
  coat1:
    home: [5, 16]
    away: [6, 15]
  coat2:
    home: [7, 14]
    away: [8, 13]
sequence21:
  coat1:
    home: [1, 12]
    away: [2, 11]
  coat2:
    home: [3, 14]
    away: [4, 13]
sequence22:
  coat1:
    home: [5, 10]
    away: [6, 9]
  coat2:
    home: [7, 16]
    away: [8, 15]
sequence23:
  coat1:
    home: [1, 14]
    away: [2, 13]
  coat2:
    home: [3, 16]
    away: [4, 15]
sequence24:
  coat1:
    home: [5, 12]
    away: [6, 11]
  coat2:
    home: [7, 10]
    away: [8, 9]
sequence25:
  coat1:
    home: [1, 16]
    away: [2, 15]
  coat2:
    home: [3, 10]
    away: [4, 9]
sequence26:
  coat1:
    home: [5, 14]
    away: [6, 13]
  coat2:
    home: [7, 12]
    away: [8, 11]
sequence27:
  coat1:
    home: [1, 8]
    away: [2, 7]
  coat2:
    home: [3, 6]
    away: [4, 5]
sequence28:
  coat1:
    home: [9, 16]
    away: [10, 15]
  coat2:
    home: [11, 14]
    away: [12, 13]
sequence29:
  coat1:
    home: [1, 4]
    away: [2, 3]
  coat2:
    home: [5, 8]
    away: [6, 7]
sequence30:
  coat1:
    home: [9, 12]
    away: [10, 11]
  coat2:
    home: [13, 16]
    away: [14, 15]
