# コート2面、プレイヤー16人
sequence1:
  coat1:
    home: [1, 2]
    away: [3, 4]
  coat2:
    home: [5, 6]
    away: [7, 8]
sequence2:
  coat1:
    home: [9, 10]
    away: [11, 12]
  coat2:
    home: [13, 14]
    away: [15, 16]
sequence3:
  coat1:
    home: [1, 3]
    away: [5, 9]
  coat2:
    home: [2, 4]
    away: [6, 7]
sequence4:
  coat1:
    home: [8, 10]
    away: [13, 15]
  coat2:
    home: [11, 14]
    away: [12, 16]
sequence5:
  coat1:
    home: [1, 4]
    away: [8, 11]
  coat2:
    home: [2, 5]
    away: [9, 12]
sequence6:
  coat1:
    home: [3, 6]
    away: [10, 14]
  coat2:
    home: [7, 15]
    away: [13, 16]
sequence7:
  coat1:
    home: [1, 7]
    away: [12, 10]
  coat2:
    home: [2, 11]
    away: [5, 8]
sequence8:
  coat1:
    home: [4, 9]
    away: [14, 15]
  coat2:
    home: [3, 13]
    away: [6, 16]
sequence9:
  coat1:
    home: [7, 12]
    away: [8, 3]
  coat2:
    home: [1, 11]
    away: [2, 6]
sequence10:
  coat1:
    home: [5, 10]
    away: [4, 16]
  coat2:
    home: [9, 14]
    away: [13, 15]
sequence11:
  coat1:
    home: [3, 9]
    away: [8, 4]
  coat2:
    home: [6, 10]
    away: [12, 5]
sequence12:
  coat1:
    home: [1, 14]
    away: [2, 7]
  coat2:
    home: [11, 15]
    away: [13, 16]
sequence13:
  coat1:
    home: [3, 7]
    away: [9, 11]
  coat2:
    home: [4, 10]
    away: [8, 2]
sequence14:
  coat1:
    home: [5, 1]
    away: [14, 16]
  coat2:
    home: [6, 13]
    away: [12, 15]
sequence15:
  coat1:
    home: [8, 9]
    away: [1, 6]
  coat2:
    home: [3, 12]
    away: [4, 11]
sequence16:
  coat1:
    home: [2, 14]
    away: [10, 13]
  coat2:
    home: [7, 16]
    away: [5, 15]
sequence17:
  coat1:
    home: [9, 7]
    away: [11, 10]
  coat2:
    home: [1, 12]
    away: [4, 5]
sequence18:
  coat1:
    home: [3, 2]
    away: [6, 15]
  coat2:
    home: [8, 13]
    away: [14, 16]
sequence19:
  coat1:
    home: [4, 7]
    away: [9, 6]
  coat2:
    home: [1, 10]
    away: [11, 3]
sequence20:
  coat1:
    home: [12, 2]
    away: [8, 16]
  coat2:
    home: [5, 13]
    away: [14, 15]
sequence21:
  coat1:
    home: [4, 6]
    away: [11, 5]
  coat2:
    home: [1, 8]
    away: [7, 10]
sequence22:
  coat1:
    home: [3, 16]
    away: [9, 2]
  coat2:
    home: [12, 14]
    away: [13, 15]
sequence23:
  coat1:
    home: [1, 9]
    away: [6, 12]
  coat2:
    home: [5, 7]
    away: [10, 3]
sequence24:
  coat1:
    home: [4, 14]
    away: [11, 16]
  coat2:
    home: [8, 15]
    away: [2, 13]
sequence25:
  coat1:
    home: [3, 5]
    away: [12, 8]
  coat2:
    home: [6, 11]
    away: [10, 2]
sequence26:
  coat1:
    home: [1, 16]
    away: [9, 13]
  coat2:
    home: [7, 14]
    away: [4, 15]
sequence27:
  coat1:
    home: [6, 8]
    away: [11, 7]
  coat2:
    home: [2, 10]
    away: [12, 4]
sequence28:
  coat1:
    home: [5, 16]
    away: [1, 15]
  coat2:
    home: [3, 14]
    away: [9, 13]
sequence29:
  coat1:
    home: [2, 9]
    away: [7, 5]
  coat2:
    home: [4, 8]
    away: [6, 10]
sequence30:
  coat1:
    home: [11, 13]
    away: [3, 15]
  coat2:
    home: [12, 14]
    away: [1, 16]
