# コート2面、プレイヤー12人
sequence1:
  coat1:
    home: [1, 2]
    away: [3, 4]
  coat2:
    home: [5, 6]
    away: [7, 8]
sequence2:
  coat1:
    home: [9, 10]
    away: [11, 12]
  coat2:
    home: [1, 3]
    away: [5, 7]
sequence3:
  coat1:
    home: [2, 4]
    away: [6, 9]
  coat2:
    home: [8, 11]
    away: [10, 12]
sequence4:
  coat1:
    home: [1, 5]
    away: [2, 10]
  coat2:
    home: [3, 7]
    away: [4, 8]
sequence5:
  coat1:
    home: [6, 11]
    away: [9, 12]
  coat2:
    home: [1, 4]
    away: [5, 8]
sequence6:
  coat1:
    home: [2, 7]
    away: [10, 11]
  coat2:
    home: [3, 9]
    away: [6, 12]
sequence7:
  coat1:
    home: [1, 8]
    away: [9, 11]
  coat2:
    home: [4, 6]
    away: [5, 10]
sequence8:
  coat1:
    home: [2, 3]
    away: [7, 12]
  coat2:
    home: [4, 5]
    away: [8, 9]
sequence9:
  coat1:
    home: [1, 11]
    away: [6, 3]
  coat2:
    home: [10, 7]
    away: [2, 12]
sequence10:
  coat1:
    home: [5, 9]
    away: [3, 10]
  coat2:
    home: [8, 6]
    away: [2, 11]
sequence11:
  coat1:
    home: [4, 7]
    away: [1, 12]
  coat2:
    home: [3, 8]
    away: [6, 10]
sequence12:
  coat1:
    home: [9, 4]
    away: [11, 7]
  coat2:
    home: [2, 1]
    away: [5, 12]
sequence13:
  coat1:
    home: [3, 5]
    away: [4, 11]
  coat2:
    home: [8, 10]
    away: [1, 9]
sequence14:
  coat1:
    home: [6, 2]
    away: [7, 12]
  coat2:
    home: [1, 10]
    away: [3, 9]
sequence15:
  coat1:
    home: [5, 11]
    away: [6, 7]
  coat2:
    home: [4, 12]
    away: [8, 2]
sequence16:
  coat1:
    home: [3, 11]
    away: [2, 5]
  coat2:
    home: [1, 6]
    away: [10, 4]
sequence17:
  coat1:
    home: [9, 7]
    away: [8, 12]
  coat2:
    home: [1, 3]
    away: [2, 6]
sequence18:
  coat1:
    home: [4, 5]
    away: [11, 12]
  coat2:
    home: [10, 9]
    away: [7, 8]
sequence19:
  coat1:
    home: [1, 7]
    away: [2, 9]
  coat2:
    home: [3, 4]
    away: [10, 11]
sequence20:
  coat1:
    home: [6, 12]
    away: [5, 8]
  coat2:
    home: [2, 3]
    away: [4, 9]
sequence21:
  coat1:
    home: [1, 7]
    away: [11, 8]
  coat2:
    home: [10, 12]
    away: [5, 6]
sequence22:
  coat1:
    home: [2, 5]
    away: [9, 8]
  coat2:
    home: [4, 7]
    away: [6, 10]
sequence23:
  coat1:
    home: [3, 12]
    away: [1, 11]
  coat2:
    home: [2, 9]
    away: [4, 6]
sequence24:
  coat1:
    home: [8, 12]
    away: [10, 3]
  coat2:
    home: [5, 1]
    away: [7, 11]
sequence25:
  coat1:
    home: [2, 11]
    away: [8, 10]
  coat2:
    home: [9, 7]
    away: [3, 5]
sequence26:
  coat1:
    home: [4, 12]
    away: [6, 1]
  coat2:
    home: [2, 10]
    away: [5, 9]
sequence27:
  coat1:
    home: [3, 12]
    away: [8, 4]
  coat2:
    home: [7, 1]
    away: [11, 6]
sequence28:
  coat1:
    home: [10, 7]
    away: [1, 4]
  coat2:
    home: [2, 8]
    away: [5, 11]
sequence29:
  coat1:
    home: [9, 12]
    away: [3, 6]
  coat2:
    home: [4, 10]
    away: [5, 7]
sequence30:
  coat1:
    home: [1, 8]
    away: [6, 9]
  coat2:
    home: [2, 12]
    away: [11, 3]
