# コート1面、プレイヤー4人
sequence1:
  coat1:
    home: [1, 2]
    away: [3, 4]
sequence2:
  coat1:
    home: [1, 3]
    away: [2, 4]
sequence3:
  coat1:
    home: [1, 4]
    away: [2, 3]
sequence4:
  coat1:
    home: [1, 2]
    away: [3, 4]
sequence5:
  coat1:
    home: [1, 3]
    away: [2, 4]
sequence6:
  coat1:
    home: [1, 4]
    away: [2, 3]
sequence7:
  coat1:
    home: [1, 2]
    away: [3, 4]
sequence8:
  coat1:
    home: [1, 3]
    away: [2, 4]
sequence9:
  coat1:
    home: [1, 4]
    away: [2, 3]
sequence10:
  coat1:
    home: [1, 2]
    away: [3, 4]
sequence11:
  coat1:
    home: [1, 3]
    away: [2, 4]
sequence12:
  coat1:
    home: [1, 4]
    away: [2, 3]
sequence13:
  coat1:
    home: [1, 2]
    away: [3, 4]
sequence14:
  coat1:
    home: [1, 3]
    away: [2, 4]
sequence15:
  coat1:
    home: [1, 4]
    away: [2, 3]
sequence16:
  coat1:
    home: [1, 2]
    away: [3, 4]
sequence17:
  coat1:
    home: [1, 3]
    away: [2, 4]
sequence18:
  coat1:
    home: [1, 4]
    away: [2, 3]
sequence19:
  coat1:
    home: [1, 2]
    away: [3, 4]
sequence20:
  coat1:
    home: [1, 3]
    away: [2, 4]
sequence21:
  coat1:
    home: [1, 4]
    away: [2, 3]
sequence22:
  coat1:
    home: [1, 2]
    away: [3, 4]
sequence23:
  coat1:
    home: [1, 3]
    away: [2, 4]
sequence24:
  coat1:
    home: [1, 4]
    away: [2, 3]
sequence25:
  coat1:
    home: [1, 2]
    away: [3, 4]
sequence26:
  coat1:
    home: [1, 3]
    away: [2, 4]
sequence27:
  coat1:
    home: [1, 4]
    away: [2, 3]
sequence28:
  coat1:
    home: [1, 2]
    away: [3, 4]
sequence29:
  coat1:
    home: [1, 3]
    away: [2, 4]
sequence30:
  coat1:
    home: [1, 4]
    away: [2, 3]
