# コート1面、プレイヤー8人
sequence1:
  coat1:
    home: [1, 2]
    away: [3, 4]
sequence2:
  coat1:
    home: [5, 6]
    away: [7, 8]
sequence3:
  coat1:
    home: [1, 5]
    away: [2, 6]
sequence4:
  coat1:
    home: [3, 7]
    away: [4, 8]
sequence5:
  coat1:
    home: [1, 3]
    away: [5, 7]
sequence6:
  coat1:
    home: [2, 4]
    away: [6, 8]
sequence7:
  coat1:
    home: [1, 7]
    away: [2, 8]
sequence8:
  coat1:
    home: [3, 5]
    away: [4, 6]
sequence9:
  coat1:
    home: [1, 6]
    away: [2, 5]
sequence10:
  coat1:
    home: [3, 8]
    away: [4, 7]
sequence11:
  coat1:
    home: [1, 4]
    away: [5, 8]
sequence12:
  coat1:
    home: [2, 3]
    away: [6, 7]
sequence13:
  coat1:
    home: [1, 8]
    away: [2, 7]
sequence14:
  coat1:
    home: [3, 6]
    away: [4, 5]
sequence15:
  coat1:
    home: [1, 2]
    away: [5, 6]
sequence16:
  coat1:
    home: [3, 4]
    away: [7, 8]
sequence17:
  coat1:
    home: [1, 5]
    away: [3, 7]
sequence18:
  coat1:
    home: [2, 6]
    away: [4, 8]
sequence19:
  coat1:
    home: [1, 3]
    away: [2, 4]
sequence20:
  coat1:
    home: [5, 7]
    away: [6, 8]
sequence21:
  coat1:
    home: [1, 7]
    away: [4, 6]
sequence22:
  coat1:
    home: [2, 8]
    away: [3, 5]
sequence23:
  coat1:
    home: [1, 6]
    away: [3, 8]
sequence24:
  coat1:
    home: [2, 5]
    away: [4, 7]
sequence25:
  coat1:
    home: [1, 4]
    away: [6, 7]
sequence26:
  coat1:
    home: [2, 3]
    away: [5, 8]
sequence27:
  coat1:
    home: [1, 8]
    away: [4, 5]
sequence28:
  coat1:
    home: [2, 7]
    away: [3, 6]
sequence29:
  coat1:
    home: [1, 2]
    away: [7, 8]
sequence30:
  coat1:
    home: [3, 4]
    away: [5, 6]
sequence31:
  coat1:
    home: [1, 5]
    away: [4, 8]
sequence32:
  coat1:
    home: [2, 6]
    away: [3, 7]
sequence33:
  coat1:
    home: [1, 3]
    away: [6, 8]
sequence34:
  coat1:
    home: [2, 4]
    away: [5, 7]
sequence35:
  coat1:
    home: [1, 7]
    away: [3, 5]
sequence36:
  coat1:
    home: [2, 8]
    away: [4, 6]
sequence37:
  coat1:
    home: [1, 6]
    away: [4, 7]
sequence38:
  coat1:
    home: [2, 5]
    away: [3, 8]
sequence39:
  coat1:
    home: [1, 4]
    away: [2, 3]
sequence40:
  coat1:
    home: [5, 8]
    away: [6, 7]
sequence41:
  coat1:
    home: [1, 8]
    away: [3, 6]
sequence42:
  coat1:
    home: [2, 7]
    away: [4, 5]
sequence43:
  coat1:
    home: [1, 2]
    away: [5, 6]
sequence44:
  coat1:
    home: [3, 4]
    away: [7, 8]
sequence45:
  coat1:
    home: [1, 5]
    away: [2, 6]
sequence46:
  coat1:
    home: [3, 7]
    away: [4, 8]
sequence47:
  coat1:
    home: [1, 3]
    away: [5, 7]
sequence48:
  coat1:
    home: [2, 4]
    away: [6, 8]
sequence49:
  coat1:
    home: [1, 7]
    away: [2, 8]
sequence50:
  coat1:
    home: [3, 5]
    away: [4, 6]
sequence51:
  coat1:
    home: [1, 6]
    away: [2, 5]
sequence52:
  coat1:
    home: [3, 8]
    away: [4, 7]
sequence53:
  coat1:
    home: [1, 4]
    away: [5, 8]
sequence54:
  coat1:
    home: [2, 3]
    away: [6, 7]
sequence55:
  coat1:
    home: [1, 8]
    away: [2, 7]
sequence56:
  coat1:
    home: [3, 6]
    away: [4, 5]
