# コート2面、プレイヤー10人
sequence1:
  coat1:
    home: [1, 2]
    away: [3, 4]
  coat2:
    home: [5, 6]
    away: [7, 8]
sequence2:
  coat1:
    home: [9, 10]
    away: [1, 5]
  coat2:
    home: [2, 3]
    away: [6, 7]
sequence3:
  coat1:
    home: [4, 9]
    away: [8, 10]
  coat2:
    home: [1, 3]
    away: [5, 7]
sequence4:
  coat1:
    home: [2, 6]
    away: [4, 10]
  coat2:
    home: [8, 9]
    away: [3, 7]
sequence5:
  coat1:
    home: [5, 9]
    away: [2, 4]
  coat2:
    home: [1, 10]
    away: [6, 8]
sequence6:
  coat1:
    home: [3, 5]
    away: [4, 6]
  coat2:
    home: [7, 2]
    away: [1, 8]
sequence7:
  coat1:
    home: [9, 7]
    away: [10, 6]
  coat2:
    home: [2, 5]
    away: [3, 8]
sequence8:
  coat1:
    home: [1, 4]
    away: [9, 10]
  coat2:
    home: [3, 6]
    away: [5, 8]
sequence9:
  coat1:
    home: [2, 9]
    away: [7, 1]
  coat2:
    home: [4, 8]
    away: [10, 3]
sequence10:
  coat1:
    home: [5, 4]
    away: [7, 10]
  coat2:
    home: [6, 2]
    away: [1, 9]
sequence11:
  coat1:
    home: [3, 9]
    away: [2, 10]
  coat2:
    home: [1, 6]
    away: [4, 7]
sequence12:
  coat1:
    home: [8, 2]
    away: [5, 10]
  coat2:
    home: [3, 4]
    away: [6, 9]
sequence13:
  coat1:
    home: [1, 7]
    away: [5, 8]
  coat2:
    home: [2, 3]
    away: [6, 10]
sequence14:
  coat1:
    home: [4, 9]
    away: [7, 8]
  coat2:
    home: [1, 10]
    away: [5, 3]
sequence15:
  coat1:
    home: [2, 9]
    away: [6, 5]
  coat2:
    home: [1, 8]
    away: [4, 7]
sequence16:
  coat1:
    home: [3, 8]
    away: [1, 9]
  coat2:
    home: [10, 2]
    away: [6, 7]
sequence17:
  coat1:
    home: [4, 10]
    away: [5, 7]
  coat2:
    home: [3, 6]
    away: [8, 9]
sequence18:
  coat1:
    home: [1, 4]
    away: [2, 5]
  coat2:
    home: [3, 9]
    away: [7, 10]
sequence19:
  coat1:
    home: [6, 8]
    away: [1, 5]
  coat2:
    home: [2, 4]
    away: [3, 7]
sequence20:
  coat1:
    home: [10, 8]
    away: [1, 2]
  coat2:
    home: [9, 6]
    away: [4, 5]
sequence21:
  coat1:
    home: [2, 8]
    away: [4, 6]
  coat2:
    home: [7, 9]
    away: [5, 10]
sequence22:
  coat1:
    home: [3, 10]
    away: [1, 6]
  coat2:
    home: [2, 7]
    away: [5, 9]
sequence23:
  coat1:
    home: [4, 8]
    away: [1, 3]
  coat2:
    home: [2, 6]
    away: [7, 10]
sequence24:
  coat1:
    home: [5, 1]
    away: [9, 3]
  coat2:
    home: [4, 8]
    away: [2, 10]
sequence25:
  coat1:
    home: [6, 9]
    away: [1, 8]
  coat2:
    home: [7, 5]
    away: [3, 4]
sequence26:
  coat1:
    home: [10, 6]
    away: [1, 7]
  coat2:
    home: [2, 8]
    away: [5, 9]
sequence27:
  coat1:
    home: [3, 8]
    away: [4, 10]
  coat2:
    home: [1, 6]
    away: [2, 5]
sequence28:
  coat1:
    home: [7, 3]
    away: [9, 4]
  coat2:
    home: [5, 6]
    away: [8, 10]
sequence29:
  coat1:
    home: [1, 3]
    away: [2, 7]
  coat2:
    home: [4, 6]
    away: [9, 10]
sequence30:
  coat1:
    home: [8, 7]
    away: [2, 3]
  coat2:
    home: [5, 4]
    away: [1, 9]
