# コート2面、プレイヤー13人
sequence1:
  coat1:
    home: [1, 2]
    away: [3, 4]
  coat2:
    home: [5, 6]
    away: [7, 8]
sequence2:
  coat1:
    home: [9, 10]
    away: [11, 12]
  coat2:
    home: [13, 1]
    away: [2, 5]
sequence3:
  coat1:
    home: [3, 6]
    away: [9, 13]
  coat2:
    home: [4, 7]
    away: [8, 10]
sequence4:
  coat1:
    home: [11, 1]
    away: [12, 6]
  coat2:
    home: [2, 3]
    away: [5, 7]
sequence5:
  coat1:
    home: [4, 8]
    away: [13, 11]
  coat2:
    home: [9, 12]
    away: [10, 2]
sequence6:
  coat1:
    home: [1, 7]
    away: [9, 11]
  coat2:
    home: [3, 5]
    away: [6, 10]
sequence7:
  coat1:
    home: [4, 12]
    away: [8, 13]
  coat2:
    home: [2, 7]
    away: [1, 6]
sequence8:
  coat1:
    home: [5, 9]
    away: [11, 4]
  coat2:
    home: [3, 10]
    away: [8, 12]
sequence9:
  coat1:
    home: [13, 2]
    away: [7, 10]
  coat2:
    home: [1, 9]
    away: [5, 8]
sequence10:
  coat1:
    home: [6, 4]
    away: [3, 12]
  coat2:
    home: [11, 2]
    away: [13, 5]
sequence11:
  coat1:
    home: [7, 6]
    away: [10, 4]
  coat2:
    home: [1, 3]
    away: [8, 11]
sequence12:
  coat1:
    home: [9, 7]
    away: [12, 13]
  coat2:
    home: [2, 6]
    away: [1, 8]
sequence13:
  coat1:
    home: [5, 4]
    away: [10, 12]
  coat2:
    home: [3, 13]
    away: [11, 9]
sequence14:
  coat1:
    home: [2, 8]
    away: [10, 11]
  coat2:
    home: [1, 4]
    away: [7, 3]
sequence15:
  coat1:
    home: [6, 13]
    away: [5, 12]
  coat2:
    home: [9, 8]
    away: [2, 4]
sequence16:
  coat1:
    home: [1, 5]
    away: [10, 13]
  coat2:
    home: [3, 11]
    away: [7, 12]
sequence17:
  coat1:
    home: [6, 9]
    away: [1, 10]
  coat2:
    home: [8, 3]
    away: [5, 11]
sequence18:
  coat1:
    home: [2, 12]
    away: [4, 9]
  coat2:
    home: [7, 13]
    away: [6, 8]
sequence19:
  coat1:
    home: [11, 6]
    away: [2, 9]
  coat2:
    home: [1, 12]
    away: [5, 10]
sequence20:
  coat1:
    home: [3, 7]
    away: [4, 13]
  coat2:
    home: [8, 5]
    away: [2, 9]
sequence21:
  coat1:
    home: [10, 12]
    away: [11, 7]
  coat2:
    home: [1, 6]
    away: [4, 13]
sequence22:
  coat1:
    home: [3, 9]
    away: [7, 10]
  coat2:
    home: [5, 11]
    away: [4, 6]
sequence23:
  coat1:
    home: [2, 8]
    away: [12, 3]
  coat2:
    home: [1, 4]
    away: [13, 9]
sequence24:
  coat1:
    home: [5, 1]
    away: [7, 12]
  coat2:
    home: [6, 13]
    away: [10, 11]
sequence25:
  coat1:
    home: [2, 10]
    away: [3, 8]
  coat2:
    home: [4, 9]
    away: [5, 6]
sequence26:
  coat1:
    home: [1, 13]
    away: [12, 8]
  coat2:
    home: [7, 2]
    away: [11, 3]
sequence27:
  coat1:
    home: [4, 10]
    away: [1, 11]
  coat2:
    home: [5, 9]
    away: [7, 8]
sequence28:
  coat1:
    home: [6, 12]
    away: [2, 3]
  coat2:
    home: [13, 8]
    away: [7, 9]
sequence29:
  coat1:
    home: [5, 13]
    away: [10, 3]
  coat2:
    home: [1, 2]
    away: [4, 11]
sequence30:
  coat1:
    home: [6, 7]
    away: [12, 2]
  coat2:
    home: [9, 10]
    away: [3, 4]
