# コート1面、プレイヤー5人
sequence1:
  coat1:
    home: [1, 2]
    away: [3, 4]
sequence2:
  coat1:
    home: [5, 1]
    away: [2, 3]
sequence3:
  coat1:
    home: [4, 5]
    away: [1, 3]
sequence4:
  coat1:
    home: [2, 4]
    away: [5, 3]
sequence5:
  coat1:
    home: [1, 4]
    away: [2, 5]
sequence6:
  coat1:
    home: [3, 1]
    away: [2, 4]
sequence7:
  coat1:
    home: [5, 3]
    away: [1, 2]
sequence8:
  coat1:
    home: [4, 3]
    away: [5, 1]
sequence9:
  coat1:
    home: [2, 3]
    away: [4, 5]
sequence10:
  coat1:
    home: [1, 4]
    away: [2, 5]
sequence11:
  coat1:
    home: [3, 2]
    away: [1, 4]
sequence12:
  coat1:
    home: [5, 2]
    away: [1, 3]
sequence13:
  coat1:
    home: [4, 3]
    away: [5, 1]
sequence14:
  coat1:
    home: [2, 4]
    away: [5, 3]
sequence15:
  coat1:
    home: [1, 2]
    away: [4, 5]
sequence16:
  coat1:
    home: [3, 2]
    away: [1, 4]
sequence17:
  coat1:
    home: [5, 2]
    away: [1, 3]
sequence18:
  coat1:
    home: [4, 3]
    away: [5, 1]
sequence19:
  coat1:
    home: [2, 4]
    away: [5, 3]
sequence20:
  coat1:
    home: [1, 2]
    away: [4, 5]
sequence21:
  coat1:
    home: [3, 1]
    away: [2, 4]
sequence22:
  coat1:
    home: [5, 1]
    away: [2, 3]
sequence23:
  coat1:
    home: [4, 1]
    away: [5, 3]
sequence24:
  coat1:
    home: [2, 5]
    away: [4, 3]
sequence25:
  coat1:
    home: [1, 2]
    away: [4, 5]
sequence26:
  coat1:
    home: [3, 4]
    away: [1, 2]
sequence27:
  coat1:
    home: [5, 1]
    away: [2, 3]
sequence28:
  coat1:
    home: [4, 5]
    away: [1, 3]
sequence29:
  coat1:
    home: [2, 4]
    away: [5, 3]
sequence30:
  coat1:
    home: [1, 4]
    away: [2, 5]
